### ISSUE TITLE
"Plugin ID mismatch" when click the plugin in obsidian

### ISSUE THREAD

**Issue by troilus** [ludovicchabant/obsidian-remember-file-state#1]

**Comment by claremacrae** [comment]
I just came here to report the same problem.

When running the script that updates the Obsidian Hub's list of community plugins, a consistency check failed for this plugin.

The output is:

```text
ERROR repo:ludovicchabant/obsidian-remember-file-state ID obsidian-remember-file-state
does not match ID in manifest: remember-file-state
```

**Comment by ReaderGuy42** [comment]
I'm getting the same message.

**Comment by ludovicchabant** [comment]
Fixed now! Sorry about the trouble.

**Comment by claremacrae** [comment]
Super - thanks very much indeed.
