### ISSUE TITLE
Doesn't work with multiple panes showing the same file

### ISSUE THREAD

**Issue by hsandt** [ludovicchabant/obsidian-remember-file-state#12]
I found an edge case where I forgot to close one of my panes showing the same file as my main pane. This caused the main pane to keep going back to the position of the duplicate pane (here, at the top).

This is probably due to position being stored by file and doesn't know about panes. If you don't intend to fix this, I'll understand. I'll just make sure to close duplicate panes. You can add it in some Caveats list on README if you want.

**Comment by ludovicchabant** [comment]
Hi!
I can't reproduce the bug so far... do you have specific steps for me to follow?
FWIW the plugin won't restore the scroll/selection state of a file view if the file is already open in other panes. In that case, the file is open at the top.

**Comment by hsandt** [comment]
I see, the bug only occurred when the file was opened in another pane indeed (1. Open same file in new pane - visible or not, I think it doesn't matter, 2. Switch to another file in first pane, then back to file opened in two panes). But I see this is by design, and I don't often have the same file in multiple panes (it just happens by accident) so it's okay.

For people who really need this, I found out that another plugin https://github.com/dy-sh/obsidian-remember-cursor-position supports duplicate panes. However, it does not have certain features like remembering text selection.

**Comment by ludovicchabant** [comment]
Hi!  Thanks for the repro... It looks like that other plugin actually _ignores_ panes and always restores the last remembered state regardless of the pane. Maybe I should do the same, instead of doing something that ends up being counter productive? I wrote something that I thought would be _less_ confusing, but it seems that it ends up being _more_ confusing... 😅

**Comment by ludovicchabant** [comment]
FWIW [version 1.1.0](https://github.com/ludovicchabant/obsidian-remember-file-state/releases/tag/1.1.0) should now handle this better!

**Comment by hsandt** [comment]
Thanks! The two plugins seem to work in a similar way now. I only lost my scrolling on one tab once after a quick switch to other file > switch back to original file. From there, the scrolling state was properly remembered and even after closing tab, the scrolling position on that tab side would be restored (instead of copying the scrolling position of the other tab on the other side).

Looks like the other plugin (Remember cursor position) also improved and also remembers text selection now! Maybe it's a coincidence, or maybe you're really pulling each other up!
