### ISSUE TITLE
Not working after update to 1.4.5

### ISSUE THREAD

**Issue by guihasparyk** [ludovicchabant/obsidian-remember-file-state#14]
After update to Obsidian Windows Version 1.4.5 on Win10 the file state is not saved anymore.

**Comment by ludovicchabant** [comment]
Can you try upgrading both Obsidian and the plugin?  It seems to work fine here with the latest of both (Obsidian 1.4.13 and remember-file-state 1.1.0)

**Comment by guihasparyk** [comment]
That was it. Thank you very much. Keep on the good work.
