### ISSUE TITLE
Does not work on Android

### ISSUE THREAD

**Issue by Charles7z** [ludovicchabant/obsidian-remember-file-state#15]
Nothing happens at all on Android obsidian 🥴

Tried it several times in each view mode, document opens at top every time.

**Comment by guihasparyk** [comment]
Same problem here. It's a shame because this plugin is was perfect workflow.

**Comment by ludovicchabant** [comment]
Sadly I don't have any Android device to troubleshoot this... if anybody with some coding experience is able to help, I'll gladly take it!

**Comment by guihasparyk** [comment]
Well, form me it got back to working again.

**Comment by ludovicchabant** [comment]
Oh well... I don't know what could have caused it, but glad it got fixed!
