### ISSUE TITLE
Not working in PC

### ISSUE THREAD

**Issue by guihasparyk** [ludovicchabant/obsidian-remember-file-state#17]
I have Obsidian v1.4.14 and Remember File State v1.1.0

That states are note being saved at all.

**Comment by ludovicchabant** [comment]
Can you open the developer console (`Shift+Ctrl+I`, I think, or "Toggle Developer Tools" in the view menu), open and close a few notes, and see if any error message shows up in the console? For extra info, make sure to enable the "Verbose" log level in the drop down next to the "filter" box in the console.

**Comment by guihasparyk** [comment]
It started working now. 

Thank you for the help.
