### ISSUE TITLE
How is this different from Remember Cursor Position?

### ISSUE THREAD

**Issue by Triquetra** [ludovicchabant/obsidian-remember-file-state#19]
This seems to do the same thing as [Remember Cursor Position](https://github.com/dy-sh/obsidian-remember-cursor-position).

What distinguishes this plugin from that one?

**Comment by xjn6666** [comment]
I have the same question

**Comment by ludovicchabant** [comment]
Mainly that this one doesn't rely on adding timers that contribute to slowing down the UI.
