### ISSUE TITLE
Selection points outside of document

### ISSUE THREAD

**Issue by esm7** [ludovicchabant/obsidian-remember-file-state#2]
Hey,
Your plugin is exactly what I was looking for and I'm really happy the version got fixed yesterday :sunglasses: 
However, in my first attempts to use it, there were many cases that opening a previously-closed file led to this error:
```
Uncaught (in promise) RangeError: Selection points outside of document
    at nr (app.js:1)
    at new e (app.js:1)
    at zr (app.js:1)
    at e.update (app.js:1)
    at RememberFileStatePlugin.restoreFileState (eval at <anonymous> (app.js:1), <anonymous>:200:48)
    at RememberFileStatePlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:165:18)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:46:61)
    at new Promise (<anonymous>)
    at __async (eval at <anonymous> (app.js:1), <anonymous>:30:10)
```

**Comment by ludovicchabant** [comment]
Since the plugin has only been tested on my machine, I'm not surprised :) 

Did the file you reopened happen to have been changed outside of Obsidian during that time?

**Comment by esm7** [comment]
No, I only used Obsidian on my desktop computer, changed the file, went through a few files and came back.

**Comment by ludovicchabant** [comment]
Ok, I'll test some more to see if I can repro it, and just add some error catching around that point in the meantime.

**Comment by ludovicchabant** [comment]
I wasn't able to reproduce your issue -- if you figure out what's happening, please reopen this ticket. In the meantime, I added some simple `try/catch`: fca12298d078df3d2f099088d8b516e7e1772555

**Comment by esm7** [comment]
Honestly this happens so much that I gave up and stopped using the plugin...

**Comment by ludovicchabant** [comment]
@esm7 what other plugins did you have active at the time? Maybe it doesn't play nice with one of them
