### ISSUE TITLE
Error asking user to disable legacy editor when no such option exists in Obsidian 1.5, legacy editor no longer exists

### ISSUE THREAD

**Issue by dhry** [ludovicchabant/obsidian-remember-file-state#21]
Since Obsidian 1.5 came out I am seeing the following error on startup.

![image](https://github.com/ludovicchabant/obsidian-remember-file-state/assets/4991066/149a4199-f28f-4d82-b4e5-5d143c6f9f88)

The legacy editor doesn't even exist anymore, let alone an option to disable it. It has been completely removed from Obsidian thus not sure why this error is appearing.

**Comment by ludovicchabant** [comment]
Weird, I'm not seeing that warning... but I assume it might have to do with some leftover value in your configuration file, or something. But yes, I can remove that check now.

Fixed with b79a7abb5d9bcaf6bffa4111e6ba1700f14636c6, published as 1.1.2. Thanks!

**Comment by dhry** [comment]
Thank you for the fix!!
