### ISSUE TITLE
Conflict: Hover preview jumps to the current location of a block reference from the same document, not the location of the referenced block.

### ISSUE THREAD

**Issue by hujie12306** [ludovicchabant/obsidian-remember-file-state#3]
Conflict: Hover preview jumps to the current location of a block reference from the same document, not the location of the referenced block.
I want to mask the jump to the current location when previewing block references (text references) of the same document

**Comment by hujie12306** [comment]
My English is poor.
冲突:当悬浮预览引自同一文档的块引用时会跳到当前位置，而不是留在引用的块的位置。
希望在预览预览的同一文档的块引用(文本引用)时可以屏蔽跳转当前位置

**Comment by ludovicchabant** [comment]
I don't understand how to reproduce the bug. Could you capture the bug in a GIF and post it here?

**Comment by hujie12306** [comment]
I seem to have made a mistake. It's the floating preview BUG.
