### ISSUE TITLE
The plugin does not work?

### ISSUE THREAD

**Issue by chumido98** [ludovicchabant/obsidian-remember-file-state#6]
I'm using the lastest version of both obsidian and plugin
I opened a note (just 1 note) -> scroll and click at a line -> i close the note -> open it again, but the cursor still on top.
Anything i missed? Can someone help?

**Comment by dwSun** [comment]
+1
opened a note A -> switch to reading mode -> switch to other notes -> switch to editing mode  ->  switch back to note A
Note A is in editing mode.

**Comment by lucible** [comment]
I am also encountering this issue on Obsidian v0.15.9 -- reproduced using the same steps as dwSun listed.

**Comment by ludovicchabant** [comment]
Hello! Note that the plugin doesn't work if you're using the legacy editor (which was the default until very recently), and that the upcoming 0.16, which adds a tabbed interface, effectively renders this plugin obsolete.

**Comment by ludovicchabant** [comment]
Recent versions of Obsidian now default to using the new editor (the Legacy Editor option is turned off by default). AFAICT this plugin still works OK with tabbed interface, too. You can open a new issue if necessary.
