### ISSUE TITLE
Support for obsidian zoom

### ISSUE THREAD

**Issue by tonyxiao** [ludovicchabant/obsidian-remember-file-state#8]
it would be amazing if it could remember where the user is during obsidian zoom https://github.com/vslinko/obsidian-zoom

Losing state of the zoom is one of the most annoying things currently about the way obsidian works (vs. something like roam)

**Comment by ludovicchabant** [comment]
It seems brittle for one plugin to try and save/restore the state of another plugin -- any of the two could break one another. You could reach out to @vslinko about this -- my plugin could potentially offer some simple API that other plugins could use to save/restore state on open files.
