### ISSUE TITLE
Have the file state in sync

### ISSUE THREAD

**Issue by dxps** [ludovicchabant/obsidian-remember-file-state#9]
First of all, this is a great plugin and thanks a lot for creating and sharing it! :pray: :blush: 

I'm having one comment about it: since I'm sync-ing my notes through a Git repo, I'd like to have the files states managed by this plugin synced as well.

Currently in `.obsidian/plugins/obsidian-remember-file-state/` this plugin keeps the only setting it currrently has. I don't know this state is remembered as file. And if that file is also captured in that plugin's directory, then all should be kept in sync.

So, my question is: can we have the files states sync'd as well? :blush: 

Thanks!

**Comment by ludovicchabant** [comment]
Maybe one day :D But no ETA and no promises. I'm closing this as a duplicate of https://github.com/ludovicchabant/obsidian-remember-file-state/issues/11 for now.
